### ISSUE TITLE
Token creation logzio in otel-collector

### ISSUE THREAD

**Issue by sagartp24** [dawidborycki/otel.logz.io#1]
Hi All,
we were trying this Opentelemetry jaeger, and tried to bring up the containers to understand the working of Opentelemetry and jaeger.

otel-collector container is failing saying " **error creating logzio exporter: `account_token` not specified**" 

How do we generate these token to mention in the config.yaml ?

**Comment by dawidborycki** [comment]
"Provide your Logz.io account token, and region under the config.yml" Please refer to logzio documentation of how to create a token

**Comment by sagartp24** [comment]
Thank you @dawidborycki
